repos:
  - repo: https://github.com/ambv/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3.11
        stages: [commit]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: check-yaml
        stages: [commit]
      - id: check-added-large-files
        stages: [commit]
      - id: mixed-line-ending
        stages: [commit]
        args:
          - --fix=auto
      - id: trailing-whitespace
        stages: [commit]
      - id: flake8
        stages: [commit]
        args: ["--max-line-length", "100"]

  - repo: local
    hooks:
      - id: pytest-check
        stages: [push]
        types: [python]
        name: pytest-check
        entry: py -m pytest
        language: system
        pass_filenames: false
        always_run: true